#server:
#  port: 8001
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/online_edu?serverTimezone=GMT%2B8
#    username: root
#    password: 123456
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  cloud:
#    nacos:
#      discovery:
#        server-addr: server:8848
#  redis:
#    host: server
#    port: 6379
#    database: 0
#    timeout: 1800000
#    password: 123456
#    lettuce:
#      pool:
#        max-active: 20
#        max-wait: -1
#        max-idle: 5
#        min-idle: 0
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath*:com/feng/eduservice/mapper/xml/*.xml
#feign:
#  hystrix:
#    enabled: true
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 6000
